basic:
  build:
  - github.com/go-chassis/go-chassis
  install: 
  - github.com/go-chassis/go-chassis/internal/cmd/dsfconfcheck
  - github.com/go-chassis/go-chassis/internal/cmd/dsferr
  test:
  - github.com/go-chassis/go-chassis/internal/...
  - github.com/go-chassis/go-chassis
  - github.com/go-chassis/go-chassis/api/errorcode
  sttest:
advance:
  conf:
  - package: github.com/go-chassis/go-chassis/conf
    to: conf
    exclude: 
    include: 
  tools:
  - package: /bin/dsfconfcheck
    to: tools/dsf
  - package: /bin/dsferr
    to: tools/dsf
property:	
  version: V600R001C10
  author: DSF
  product name: dsf