version: '3'
services:
  mongo:
    image: mongo:3.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: kie
      MONGO_INITDB_ROOT_USERNAME: kie
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - ./db.js:/docker-entrypoint-initdb.d/db.js:ro
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kie
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
  servicecomb-kie:
    image: servicecomb/kie:0.1.0
    restart: always
    ports:
      - 30110:30110
    environment:
      MONGODB_USER: kie
      MONGODB_PWD: 123
      MONGODB_ADDR: mongo
  etcd:
    image: 'quay.io/coreos/etcd:latest'
    # restart: always
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER: default=http://etcd:2380

  service-center:
    depends_on:
      - etcd
    image: 'servicecomb/service-center:latest'
    ports:
      - "30100:30100"
    environment:
      BACKEND_ADDRESS: etcd:2379

  scfrontend:
    depends_on:
      - service-center
    image: 'servicecomb/scfrontend:latest'
    ports:
      - "30103:30103"
    environment:
      SC_ADDRESS: http://service-center:30100
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
volumes:
  grafana_data: